version: "3.8"

services:
  pulsecode-ml:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ./models/saved:/app/models/saved
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Optional: Add PostgreSQL for production database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: pulsecode
      POSTGRES_USER: pulsecode
      POSTGRES_PASSWORD: pulsecode_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
